allowed-names:
- 'Bilbo'

guis:
  categories:
    itemNames:
      playerBuffs: '&aPlayerBuffs'
      weaponEnchants: '&aWeapon Enchants'
prices:
  '1':
    cost: 10
  '2':
    cost: 20
  '3':
    cost: 30
  '4':
    cost: 40
  '5':
    cost: 50
  '6':
    cost: 60
  '7':
    cost: 70
  '8':
    cost: 80
  '9':
    cost: 90
  '10':
    cost: 100